import type { DashboardData, DashboardLead, SessionProfile } from "./types";

const demoLeads: DashboardLead[] = [
  {
    id: 101,
    contactAnswer: "Possui CNPJ ativo",
    contactName: "Marina Costa",
    phone: "(11) 98888-0101",
    email: "marina@meta.com",
    companyName: "Meta Serviços Integrados",
    campaignName: "WTG - Planilha Mock",
    sellerName: "Renato",
    assignmentStatus: "assigned",
    qualificationStatus: "pending",
    conversionStatus: "active",
    commercialStatus: "undefined",
    sourceEnteredAt: "2026-08-25T12:15:00.000Z",
    feedbackDueAt: "2026-08-26T10:00:00.000Z",
    lastActivityAt: "2026-08-25T17:45:00.000Z",
    attemptsCount: 2,
    stage: "overdue",
    isBlockedBySla: true,
  },
  {
    id: 102,
    contactAnswer: "MEI em abertura",
    contactName: "Rafael Nunes",
    phone: "(11) 97777-0202",
    email: "rafael@exemplo.com",
    companyName: "Rafael Nunes Studio",
    campaignName: "WTG - Planilha Mock",
    sellerName: "Sandra",
    assignmentStatus: "assigned",
    qualificationStatus: "pending",
    conversionStatus: "active",
    commercialStatus: "negotiation",
    sourceEnteredAt: "2026-08-26T11:00:00.000Z",
    feedbackDueAt: "2026-08-26T21:00:00.000Z",
    lastActivityAt: "2026-08-26T11:05:00.000Z",
    attemptsCount: 1,
    stage: "today",
    isBlockedBySla: false,
  },
  {
    id: 103,
    contactAnswer: "Sem CNPJ",
    contactName: "Bianca Ramos",
    phone: "(11) 96666-0303",
    email: "bianca@exemplo.com",
    companyName: "Bianca Ramos Consultoria",
    campaignName: "WTG - Planilha Mock",
    sellerName: "Jessica",
    assignmentStatus: "assigned",
    qualificationStatus: "disqualified",
    conversionStatus: "closed_no_conversion",
    commercialStatus: "disqualified",
    sourceEnteredAt: "2026-08-24T14:00:00.000Z",
    feedbackDueAt: null,
    lastActivityAt: "2026-08-25T13:30:00.000Z",
    attemptsCount: 5,
    stage: "none",
    isBlockedBySla: false,
  },
  {
    id: 104,
    contactAnswer: "CNPJ com interesse",
    contactName: "Lucas Pereira",
    phone: "(11) 95555-0404",
    email: "lucas@exemplo.com",
    companyName: "Pereira Comércio",
    campaignName: "WTG - Planilha Mock",
    sellerName: "Nelma",
    assignmentStatus: "assigned",
    qualificationStatus: "qualified",
    conversionStatus: "won",
    commercialStatus: "won",
    sourceEnteredAt: "2026-08-22T09:40:00.000Z",
    feedbackDueAt: null,
    lastActivityAt: "2026-08-25T20:10:00.000Z",
    attemptsCount: 3,
    stage: "none",
    isBlockedBySla: false,
  },
];

export function getDemoDashboardData(profile: SessionProfile): DashboardData {
  const leads =
    profile.role === "admin"
      ? demoLeads
      : demoLeads.filter(
          (lead) => lead.sellerName.toLowerCase() === profile.fullName.toLowerCase(),
        );
  const names = [...new Set(leads.map((lead) => lead.sellerName))];
  return {
    leads,
    queue: names.map((sellerName, index) => ({
      sellerId: `demo-${index}`,
      sellerName,
      email: "",
      position: index + 1,
      isPaused: false,
      skipBalance: 0,
      activeLeads: leads.filter((lead) => lead.sellerName === sellerName).length,
      overdueLeads: leads.filter(
        (lead) => lead.sellerName === sellerName && lead.stage === "overdue",
      ).length,
      nextDueAt: leads.find((lead) => lead.sellerName === sellerName)?.feedbackDueAt ?? null,
    })),
    users: [],
    history: [],
    generatedAt: new Date().toISOString(),
    source: "demo",
    warning: "Dados demonstrativos exibidos porque o Supabase local não respondeu.",
    summary: {
      total: leads.length,
      queued: leads.length,
      overdue: leads.filter((lead) => lead.stage === "overdue").length,
      pending: leads.filter((lead) => lead.qualificationStatus === "pending").length,
      won: leads.filter((lead) => lead.conversionStatus === "won").length,
      feedbacksToday: leads.filter((lead) => lead.stage === "today").length,
      attempts: leads.reduce((total, lead) => total + lead.attemptsCount, 0),
    },
  };
}
